### PR TITLE
After deleting the tenant, the user with that tenant has access to the application 3864

### LINKED ISSUE #3864: After deleting the tenant, the user with that tenant has access to the application
### Environment

Jmix version: 2.4.0

### Steps To Reproduce

1) create an empty project
2) install multitenancy plugin
3) add a tenant
4) add tenant user
5) Delete tenant
6) Log in to the application using the user name of the remote tenant

### Current Behavior

After these operations, the tenant user can still log in and work in the application.

### Expected Behavior
After these operations, the tenant user cannot log in and work in the application.

### PR DESCRIPTION
**Pull request by Gavrilov-Ivan**
Fixes #3864

### CODE REVIEW

File: jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/AuthDetailsValidationResult.java [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+ */
+
+package io.jmix.securityflowui.authentication;
+
+import org.springframework.lang.Nullable;
+
+public class AuthDetailsValidationResult {
+
+    protected final boolean valid;
+    @Nullable
```
Comment (glebfox) [inline jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/AuthDetailsValidationResult.java:24]: redundant

File: jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/AuthDetailsValidationResult.java [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+        this.message = message;
+        this.exception = exception;
+    }
+
+    public static AuthDetailsValidationResult createValid() {
+        return new AuthDetailsValidationResult(true, null, null);
+    }
+
+    public static AuthDetailsValidationResult createInvalid(String message) {
+        return createInvalid(message, null);
```
Comment (glebfox) [inline jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/AuthDetailsValidationResult.java:40]: Better to check with `io.jmix.core.common.util.Preconditions#checkNotNullArgument(java.lang.Object)`

File: jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/AuthDetailsValidationResult.java [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+    }
+
+    public static AuthDetailsValidationResult createInvalid(String message, @Nullable Exception exception) {
+        return new AuthDetailsValidationResult(false, message, exception);
```
Comment (glebfox) [inline jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/AuthDetailsValidationResult.java:44]: Better to check with `io.jmix.core.common.util.Preconditions#checkNotNullArgument(java.lang.Object)`

File: jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/AuthDetailsValidationResult.java [hunk 4]
```diff
@@ -0,0 +1,60 @@
...
+package io.jmix.securityflowui.authentication;
+
+import org.springframework.lang.Nullable;
+
+public class AuthDetailsValidationResult {
+
+    protected final boolean valid;
+    @Nullable
+    protected final String message;
+    @Nullable
```
Comment (glebfox) [inline jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/AuthDetailsValidationResult.java:26]: redundant

File: jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/AuthDetailsValidationResult.java [hunk 5]
```diff
@@ -0,0 +1,60 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package io.jmix.securityflowui.authentication;
+
+import org.springframework.lang.Nullable;
+
+public class AuthDetailsValidationResult {
```
Comment (glebfox) [inline jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/AuthDetailsValidationResult.java:21]: JavaDoc + methods

File: jmix-multitenancy/multitenancy-flowui/src/main/java/io/jmix/multitenancyflowui/MultitenancyUiSupport.java [hunk 6]
```diff
@@ -27,4 +28,9 @@ public interface MultitenancyUiSupport {
     String getUsernameByTenant(String username, String tenantId);
 
     List<String> getTenantOptions();
+
+    @Nullable
+    default String extractTenantFromUsername(String username) {
```
Comment (glebfox) [inline jmix-multitenancy/multitenancy-flowui/src/main/java/io/jmix/multitenancyflowui/MultitenancyUiSupport.java:33]: JavaDoc

File: jmix-multitenancy/multitenancy-flowui/src/main/java/io/jmix/multitenancyflowui/impl/AuthDetailsTenantValidator.java [hunk 7]
```diff
@@ -0,0 +1,62 @@
...
+import io.jmix.securityflowui.authentication.AuthDetailsValidationResult;
+import io.jmix.securityflowui.authentication.AuthDetailsValidator;
+import org.springframework.lang.NonNull;
+
+import java.util.Optional;
+
+/**
+ * Implementation of {@link AuthDetailsValidator} - it checks if tenant of user exists.
+ */
+public class AuthDetailsTenantValidator implements AuthDetailsValidator {
```
Comment (glebfox) [inline jmix-multitenancy/multitenancy-flowui/src/main/java/io/jmix/multitenancyflowui/impl/AuthDetailsTenantValidator.java:33]: `TenantAuthDetailsValidator` would be preferable

File: jmix-multitenancy/multitenancy-flowui/src/main/java/io/jmix/multitenancyflowui/impl/MultitenancyUiSupportImpl.java [hunk 8]
```diff
@@ -92,6 +93,15 @@ public String getUsernameByTenant(String username, String tenantId) {
         }
     }
 
+    @Override
```
Comment (glebfox) [inline jmix-multitenancy/multitenancy-flowui/src/main/java/io/jmix/multitenancyflowui/impl/MultitenancyUiSupportImpl.java:96]: Missing `@Nullable`

**Review by glebfox — CHANGES_REQUESTED** [review]

File: jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/AuthDetailsValidationResult.java (hunk 1 above)
Comment (Gavrilov-Ivan) [reply jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/AuthDetailsValidationResult.java:24]: Done

File: jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/AuthDetailsValidationResult.java (hunk 3 above)
Comment (Gavrilov-Ivan) [reply jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/AuthDetailsValidationResult.java:44]: Done

File: jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/AuthDetailsValidationResult.java (hunk 2 above)
Comment (Gavrilov-Ivan) [reply jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/AuthDetailsValidationResult.java:40]: Added this to `createInvalid(String message, @Nullable Exception exception)` only

File: jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/AuthDetailsValidationResult.java (hunk 4 above)
Comment (Gavrilov-Ivan) [reply jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/AuthDetailsValidationResult.java:26]: Done

File: jmix-multitenancy/multitenancy-flowui/src/main/java/io/jmix/multitenancyflowui/MultitenancyUiSupport.java (hunk 6 above)
Comment (Gavrilov-Ivan) [reply jmix-multitenancy/multitenancy-flowui/src/main/java/io/jmix/multitenancyflowui/MultitenancyUiSupport.java:33]: Done

File: jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/AuthDetailsValidationResult.java (hunk 5 above)
Comment (Gavrilov-Ivan) [reply jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/AuthDetailsValidationResult.java:21]: Done

File: jmix-multitenancy/multitenancy-flowui/src/main/java/io/jmix/multitenancyflowui/impl/AuthDetailsTenantValidator.java (hunk 7 above)
Comment (Gavrilov-Ivan) [reply jmix-multitenancy/multitenancy-flowui/src/main/java/io/jmix/multitenancyflowui/impl/AuthDetailsTenantValidator.java:33]: Done

File: jmix-multitenancy/multitenancy-flowui/src/main/java/io/jmix/multitenancyflowui/impl/MultitenancyUiSupportImpl.java (hunk 8 above)
Comment (Gavrilov-Ivan) [reply jmix-multitenancy/multitenancy-flowui/src/main/java/io/jmix/multitenancyflowui/impl/MultitenancyUiSupportImpl.java:96]: Done

**Review by glebfox — APPROVED** [review]
